<?php

namespace ShareticBundle\Repository;

/**
 * ChapterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChapterRepository extends \Doctrine\ORM\EntityRepository
{
}
