<?php

namespace ShareticBundle\Repository;

/**
 * MCQAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MCQAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
