<?php

namespace ShareticBundle\Repository;

/**
 * MCQRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MCQRepository extends \Doctrine\ORM\EntityRepository
{
}
