<?php

namespace ShareticBundle\Repository;

/**
 * PoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoleRepository extends \Doctrine\ORM\EntityRepository
{
}
