<?php

namespace ShareticBundle\Repository;

/**
 * PossibleAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PossibleAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
